name: CI/CD to GCP using GHCR

on:
  push:
    branches: [ main ]

env:
  GCP_REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'  # Enable caching for dependencies
      
      - name: Install dependencies
        run: npm ci  # Faster and reliable for CI pipelines

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

  build-and-deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/swiftcloud-api:$GITHUB_SHA .
          docker tag ghcr.io/${{ github.repository }}/swiftcloud-api:$GITHUB_SHA ghcr.io/${{ github.repository }}/swiftcloud-api:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/swiftcloud-api:$GITHUB_SHA
          docker push ghcr.io/${{ github.repository }}/swiftcloud-api:latest

       - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy swiftcloud-api \
            --image ghcr.io/${{ github.repository }}/swiftcloud-api:$GITHUB_SHA \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated